### ISSUE TITLE
EPIC: Implement automated testing

### ISSUE THREAD

**Issue by yannickferenczi** [yannickferenczi/hands-home-helpers-website#91]
As a **Site Owner**, I can **rely on some automated testing** so that **the code of my website has less chance to face issues**.

---
ACCEPTANCE CRITERIA
- automated testing has been implemented on the appointments app.
- automated testing has been implemented on the config app.
- automated testing has been implemented on the contact app.
- automated testing has been implemented on the offers app.
- automated testing has been implemented on the task app.

---
TASKS
- [ ] Implement automated testing on the appointments app.
- [ ] Implement automated testing on the config app.
- [ ] Implement automated testing on the contact app.
- [ ] Implement automated testing on the offers app.
- [ ] Implement automated testing on the task app.
